// @vitest-environment node
// Opt-in synthetic SQL corpus in a separate disposable database, never DATABASE_URL.
import {beforeAll,beforeEach,afterAll,describe,expect,it} from 'vitest';
import {execFileSync,spawn} from 'node:child_process';
const container=process.env.RESEARCH_TEST_PG_CONTAINER;
const database=process.env.RESEARCH_SOURCE_TEST_DATABASE;
const enabled=Boolean(container&&database);
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const rights=id(7100),ch=id(7101),fcl=id(7102),companyDoc=id(7103),companyVersion=id(7104),companyPassage=id(7105),fromDoc=id(7110),fromVersion=id(7111),fromPassage=id(7112),toDoc=id(7120),toVersion=id(7121),toPassage=id(7122),entity=id(7130),other=id(7131),foreign=id(7132);
const q=(value:unknown)=>"'"+String(typeof value==='string'?value:JSON.stringify(value)).replaceAll("'","''")+"'";
function args(){if(!container||!/^qcs-research-test(?:-[a-z0-9]+)?$/.test(container)||database!=='research_sources_test')throw new Error('Separate source-review test database required');return ['exec','-i',container,'psql','-U','research_test','-d',database,'-v','ON_ERROR_STOP=1','-At'];}
function query(statement:string){const select=/^select\b/i.test(statement.trim());const input=select?`select coalesce(json_agg(result),'[]'::json)::text from (${statement}) result`:statement;const text=execFileSync('docker',args(),{input:input+';',encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();return select?JSON.parse(text) as Record<string,unknown>[]:[];}
function concurrent(statement:string){return new Promise<string>((resolve,reject)=>{const child=spawn('docker',args());let out='',err='';child.stdout.on('data',data=>out+=String(data));child.stderr.on('data',data=>err+=String(data));child.on('close',code=>code?reject(new Error(err)):resolve(out));child.stdin.end(statement+';');});}
const ref={documentId:companyDoc,versionId:companyVersion,passageId:companyPassage};
const caseRef={documentId:fromDoc,versionId:fromVersion,passageId:fromPassage};
const confirm=(target=entity,value='00001234')=>`select research_confirm_identifier('${target}','uk-company-number','${value}',${q(ref)}::jsonb,'source-review-test','Synthetic director identity review')`;
const treatment=(kind='overrules',quote='We overrule SYNTHETIC-TARGET for these synthetic reasons.')=>`select research_review_case_treatment('${fromDoc}','${toDoc}',${q(caseRef)}::jsonb,'${kind}',${q(quote)},'SYNTHETIC-TARGET','source-review-test','Synthetic express treatment review')`;
describe.skipIf(!enabled)('isolated persisted identity and treatment reviews',()=>{
 beforeAll(()=>{
  query(`insert into research_rights(id,holder,material,purpose,agreement_ref,agreement_hash,effective_at,transfer_conditions,retention_instructions,withdrawal_instructions,use_assessment) values('${rights}','QCS','synthetic','test','synthetic','synthetic',now()-interval '1 day','{}','{}','{}','test')`);
  for(const [source,provider]of [[ch,'companies-house'],[fcl,'find-case-law']])query(`insert into research_sources(id,label,provider,hosts,access_method,terms_url,terms_version,terms_reviewed_at,attribution,operator,purpose,rights_id,status,backfill_start,cadence_seconds,freshness_seconds,request_limit,window_seconds,daily_requests,daily_tokens,daily_pence) values('${source}','synthetic','${provider}','[]','test','https://example.test','synthetic',now(),'synthetic','QCS','test','${rights}','ready',now(),60,3600,1000,300,100,100,100)`);
  for(const [doc,version,passage,source,text,locator]of [[companyDoc,companyVersion,companyPassage,ch,'00001234',{kind:'field',value:'/company_number'}],[fromDoc,fromVersion,fromPassage,fcl,'We overrule SYNTHETIC-TARGET for these synthetic reasons.',{kind:'paragraph',value:'1'}],[toDoc,toVersion,toPassage,fcl,'Synthetic earlier authority.',{kind:'paragraph',value:'1'}]] as const){query(`insert into research_documents(id,source_id,provider_id,canonical_url,status,availability_checked_at) values('${doc}','${source}','${doc}','https://example.test/${doc}','available',now())`);query(`insert into research_versions(id,document_id,hash,retrieved_at,content_type,availability,parser_version,metadata) values('${version}','${doc}','synthetic',now(),'text/plain','available','synthetic','{"title":"Synthetic authority","identifiers":[{"type":"ukncn","value":"SYNTHETIC-TARGET"}]}')`);query(`update research_documents set current_version_id='${version}' where id='${doc}'`);query(`insert into research_passages(id,version_id,locator,text,hash) values('${passage}','${version}',${q(locator)}::jsonb,${q(text)},'synthetic')`);}
  for(const value of [entity,other])query(`insert into research_entities(id,kind,display_name,jurisdiction) values('${value}','company','Synthetic company','GB')`);
  query(`insert into research_entities(id,workspace_id,kind,display_name,jurisdiction) values('${foreign}','${id(7199)}','company','Synthetic foreign workspace','GB')`);
 });
 beforeEach(()=>{query(`delete from research_case_treatments where from_document_id='${fromDoc}'`);query(`delete from research_identifiers where entity_id in('${entity}','${other}')`);query(`update research_versions set availability='available' where id in('${companyVersion}','${fromVersion}','${toVersion}')`);query(`update research_entities set confirmed=false where id in('${entity}','${other}')`);});
 afterAll(()=>{query(`delete from research_case_treatments where from_document_id='${fromDoc}'`);query(`delete from research_identifiers where entity_id in('${entity}','${other}')`);query(`delete from research_reviews where actor='source-review-test'`);query(`delete from research_entities where id in('${entity}','${other}','${foreign}')`);query(`delete from research_passages where id in('${companyPassage}','${fromPassage}','${toPassage}')`);query(`update research_documents set current_version_id=null where id in('${companyDoc}','${fromDoc}','${toDoc}')`);query(`delete from research_versions where id in('${companyVersion}','${fromVersion}','${toVersion}')`);query(`delete from research_documents where id in('${companyDoc}','${fromDoc}','${toDoc}')`);query(`delete from research_sources where id in('${ch}','${fcl}')`);query(`delete from research_rights where id='${rights}'`);});
 it('confirms an exact source-backed number and revokes it synchronously on replacement',()=>{query(confirm());expect(query(`select confirmed from research_entities where id='${entity}'`)[0].confirmed).toBe(true);query(`update research_versions set availability='superseded' where id='${companyVersion}'`);expect(query(`select verified from research_identifiers where entity_id='${entity}'`)[0].verified).toBe(false);expect(query(`select confirmed from research_entities where id='${entity}'`)[0].confirmed).toBe(false);});
 it('rejects unsupported numbers, stale evidence and another workspace',()=>{expect(()=>query(confirm(entity,'87654321'))).toThrow();expect(()=>query(confirm(foreign))).toThrow();query(`update research_versions set availability='withdrawn' where id='${companyVersion}'`);expect(()=>query(confirm())).toThrow();expect(query(`select id from research_identifiers where entity_id='${entity}'`)).toEqual([]);});
 it('allows only one entity to win a concurrent globally unique identifier',async()=>{const results=await Promise.allSettled([concurrent(confirm(entity)),concurrent(confirm(other))]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);expect(query(`select id from research_identifiers where scheme='uk-company-number' and value='00001234' and verified`)).toHaveLength(1);});
 it('requires express treatment, records review and clears derived rationale on withdrawal',()=>{expect(()=>query(treatment('overrules','SYNTHETIC-TARGET'))).toThrow();query(treatment());expect(query(`select available,reviewed_by from research_case_treatments where from_document_id='${fromDoc}'`)[0]).toMatchObject({available:true,reviewed_by:'source-review-test'});query(`update research_versions set availability='withdrawn' where id='${toVersion}'`);expect(query(`select available,reviewed_by,reason from research_case_treatments where from_document_id='${fromDoc}'`)[0]).toEqual({available:false,reviewed_by:null,reason:''});});
});
