import {sql,type SQL} from 'drizzle-orm';
import {z} from 'zod';
import {requireDb} from './index';
import {requireResearchDirector} from '../research/roles';
import {QCS_WORKSPACE_ID} from '../research/contracts';
import {canonicalIdentifier} from '../research/entities/resolve';
import {WorkflowError} from './research-workflow';
export const identifierReviewSchema=z.object({scheme:z.string().trim().min(1).max(100),value:z.string().trim().min(1).max(500),evidence:z.object({documentId:z.uuid(),versionId:z.uuid(),passageId:z.uuid()}).strict(),reason:z.string().trim().min(20).max(2000)}).strict();
export const treatmentReviewSchema=z.object({fromDocumentId:z.uuid(),toDocumentId:z.uuid(),evidence:z.object({documentId:z.uuid(),versionId:z.uuid(),passageId:z.uuid()}).strict(),kind:z.enum(['cites','applies','distinguishes','overrules','appeal']),quotation:z.string().min(1).max(10000),targetReference:z.string().min(1).max(500),reason:z.string().trim().min(20).max(2000)}).strict();
export type ReviewedEntity={id:string;displayName:string;kind:string;jurisdiction:string|null;confirmed:boolean;identifiers:{id:string;scheme:string;value:string;verified:boolean}[]};
export async function entityRows<T>(statement:SQL):Promise<T[]>{const result=await requireDb().execute(statement);return (Array.isArray(result)?result:result.rows) as T[];}
async function mutation(statement:SQL):Promise<string>{try{const rows=await entityRows<{id:string}>(statement);if(!rows[0])throw new WorkflowError('review_not_saved',409);return rows[0].id;}catch(error){let current:unknown=error;for(let i=0;i<5&&current&&typeof current==='object';i++){const item=current as {message?:string;cause?:unknown;code?:string};if(item.code==='23505'||item.message?.includes('research_verified_identifier'))throw new WorkflowError('identifier_conflict',409);const code=item.message?.match(/\b(entity_unavailable|identifier_kind_mismatch|identifier_conflict|identifier_not_supported|treatment_not_supported|treatment_target_mismatch|express_treatment_required|review_required|evidence_unavailable)\b/)?.[1];if(code)throw new WorkflowError(code,409);current=item.cause;}throw error;}}
export async function searchReviewedEntities(input:{query?:string;scheme?:string;value?:string}):Promise<ReviewedEntity[]>{await requireResearchDirector();const query=z.string().max(300).parse(input.query??'');const identifier=input.scheme&&input.value?canonicalIdentifier({scheme:z.string().max(100).parse(input.scheme),value:z.string().max(500).parse(input.value)}):null;
 return entityRows<ReviewedEntity>(sql`SELECT e.id,e.display_name AS "displayName",e.kind,e.jurisdiction,e.confirmed,coalesce((SELECT jsonb_agg(jsonb_build_object('id',i.id,'scheme',i.scheme,'value',i.value,'verified',i.verified)) FROM research_identifiers i WHERE i.entity_id=e.id AND i.workspace_id=e.workspace_id AND EXISTS(SELECT 1 FROM research_identifier_evidence proof JOIN research_available_passages p ON p.passage_id=proof.passage_id AND p.version_id=proof.version_id AND p.document_id=proof.document_id WHERE proof.identifier_id=i.id)),'[]'::jsonb) AS identifiers FROM research_entities e WHERE e.workspace_id=${QCS_WORKSPACE_ID}::uuid AND (${query}='' OR position(lower(${query}) in lower(e.display_name))>0) AND (${identifier===null} OR EXISTS(SELECT 1 FROM research_identifiers i JOIN research_identifier_evidence proof ON proof.identifier_id=i.id JOIN research_available_passages p ON p.passage_id=proof.passage_id AND p.version_id=proof.version_id AND p.document_id=proof.document_id WHERE i.entity_id=e.id AND i.scheme=${identifier?.scheme??''} AND i.value=${identifier?.value??''} AND i.verified)) ORDER BY e.display_name,e.id LIMIT 100`);
}
export async function confirmEntityIdentifier(entityId:string,input:unknown):Promise<string>{const actor=await requireResearchDirector();z.uuid().parse(entityId);const value=identifierReviewSchema.parse(input),canonical=canonicalIdentifier(value);return mutation(sql`SELECT research_confirm_identifier(${entityId}::uuid,${canonical.scheme},${canonical.value},${JSON.stringify(value.evidence)}::jsonb,${actor},${value.reason}) AS id`);}
export async function reviewCaseTreatment(input:unknown):Promise<string>{const actor=await requireResearchDirector();const value=treatmentReviewSchema.parse(input);return mutation(sql`SELECT research_review_case_treatment(${value.fromDocumentId}::uuid,${value.toDocumentId}::uuid,${JSON.stringify(value.evidence)}::jsonb,${value.kind},${value.quotation},${value.targetReference},${actor},${value.reason}) AS id`);}
export async function listCaseTreatments(documentId:string){await requireResearchDirector();z.uuid().parse(documentId);return entityRows<{id:string;fromDocumentId:string;toDocumentId:string;kind:string;passageId:string;reviewedBy:string;reason:string;sourceTitle:string;targetTitle:string}>(sql`SELECT t.id,t.from_document_id AS "fromDocumentId",t.to_document_id AS "toDocumentId",t.kind,t.passage_id AS "passageId",t.reviewed_by AS "reviewedBy",t.reason,p.title AS "sourceTitle",v.metadata->>'title' AS "targetTitle" FROM research_case_treatments t JOIN research_available_passages p ON p.passage_id=t.passage_id AND p.version_id=t.from_version_id AND p.document_id=t.from_document_id JOIN research_documents d ON d.id=t.to_document_id AND d.current_version_id=t.to_version_id AND d.status='available' JOIN research_versions v ON v.id=d.current_version_id AND v.availability='available' JOIN research_sources s ON s.id=d.source_id JOIN research_rights r ON r.id=s.rights_id WHERE t.workspace_id=${QCS_WORKSPACE_ID}::uuid AND d.workspace_id=t.workspace_id AND t.available AND t.reviewed_by IS NOT NULL AND r.effective_at<=now() AND (r.expires_at IS NULL OR r.expires_at>now()) AND (t.from_document_id=${documentId}::uuid OR t.to_document_id=${documentId}::uuid) ORDER BY t.created_at DESC LIMIT 100`);}
