// @vitest-environment node
// Isolated synthetic corpus; never connects to DATABASE_URL.
import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { PgDialect } from 'drizzle-orm/pg-core';
import type { SQL } from 'drizzle-orm';
import { createCaseLawRepository } from './research-case-law';
const container = process.env.RESEARCH_TEST_PG_CONTAINER;
const database = process.env.RESEARCH_SOURCE_TEST_DATABASE;
const workspace = '00000000-0000-4000-8000-000000009001', source = '00000000-0000-4000-8000-000000009002', rights = '00000000-0000-4000-8000-000000009003', doc = '00000000-0000-4000-8000-000000009004', old = '00000000-0000-4000-8000-000000009005', current = '00000000-0000-4000-8000-000000009006';
function query(statement: string): Record<string, unknown>[] { if (!container || !/^qcs-research-test(?:-[a-z0-9]+)?$/.test(container) || database !== 'research_sources_test')
    throw new Error('Isolated test container required'); const select = /^select\b/i.test(statement.trim()); const command = select ? `select coalesce(json_agg(result),'[]'::json)::text from (${statement}) result` : statement; const result = execFileSync('docker', ['exec', '-i', container, 'psql', '-U', 'research_test', '-d', database, '-v', 'ON_ERROR_STOP=1', '-At'], { input: command + ';', encoding: 'utf8' }).trim(); return select ? JSON.parse(result) : []; }
const literal = (v: unknown): string => v === null ? 'NULL' : Array.isArray(v) ? `ARRAY[${v.map(literal).join(',')}]` : typeof v === 'number' ? String(v) : "'" + String(v).replaceAll("'", "''") + "'";
const execute = async (statement: SQL) => { const compiled = new PgDialect().sqlToQuery(statement); return { rows: query(compiled.sql.replace(/\$(\d+)/g, (_, n) => literal(compiled.params[Number(n) - 1]))) }; };
const repository = createCaseLawRepository({ execute } as unknown as Parameters<typeof createCaseLawRepository>[0]);
describe.skipIf(!container || !database)('isolated case-law current availability and provenance', () => {
    beforeAll(() => { query(`insert into research_rights(id,workspace_id,holder,material,purpose,agreement_ref,agreement_hash,effective_at,transfer_conditions,retention_instructions,withdrawal_instructions,use_assessment) values('${rights}','${workspace}','QCS','synthetic','test','synthetic','synthetic',now(),'{}','{}','{}','test')`); query(`insert into research_sources(id,workspace_id,label,provider,hosts,access_method,terms_url,terms_version,terms_reviewed_at,attribution,operator,purpose,rights_id,status,backfill_start,cadence_seconds,freshness_seconds,request_limit,window_seconds,daily_requests,daily_tokens,daily_pence) values('${source}','${workspace}','synthetic','find-case-law','[]','test','https://example.test','synthetic',now(),'synthetic','QCS','test','${rights}','ready',now(),60,3600,1000,300,100,100,100)`); query(`insert into research_documents(id,workspace_id,source_id,provider_id,canonical_url,status,availability_checked_at) values('${doc}','${workspace}','${source}','synthetic','https://example.test','available',now())`); for (const [id, title, availability] of [[old, 'Old synthetic', 'superseded'], [current, 'Current synthetic', 'available']])
        query(`insert into research_versions(id,workspace_id,document_id,hash,retrieved_at,published_at,content_type,availability,parser_version,metadata) values('${id}','${workspace}','${doc}','${id}',now(),'2026-09-10','application/xml','${availability}','synthetic','{"title":"${title}","identifiers":[{"type":"ukncn","value":"SYNTHETIC"}],"passageOrder":["paragraph:1","paragraph:2"],"facts":[{"predicate":"case.court","value":{"text":"TCC"}}]}')`); query(`update research_documents set current_version_id='${current}' where id='${doc}'`); for (const [version, number, text] of [[old, 1, 'Obsolete secret phrase'], [current, 2, 'Second construction paragraph'], [current, 1, 'First adjudication paragraph']])
        query(`insert into research_passages(workspace_id,version_id,locator,text,hash) values('${workspace}','${version}','{"kind":"paragraph","value":"${number}"}','${text}','${version}-${number}')`); });
    afterAll(() => { query(`delete from research_passages where workspace_id='${workspace}'`); query(`update research_documents set current_version_id=null where workspace_id='${workspace}'`); query(`delete from research_versions where workspace_id='${workspace}'`); query(`delete from research_documents where workspace_id='${workspace}'`); query(`delete from research_sources where workspace_id='${workspace}'`); query(`delete from research_rights where workspace_id='${workspace}'`); });
    it('searches current passages and applies dates, court and exact identifiers', async () => { expect(await repository.search(workspace, { query: 'adjudication', citation: 'SYNTHETIC', courts: ['TCC'], from: '2026-09-01', to: '2026-09-12' })).toHaveLength(1); expect(await repository.search(workspace, { query: 'obsolete' })).toEqual([]); expect(await repository.search(workspace, { from: '2026-09-11' })).toEqual([]); expect(await repository.search(workspace, { citation: "SYNTHETIC' OR true --" })).toEqual([]); });
    it('reads paragraphs in publisher order and rejects another workspace', async () => { const result = await repository.read(workspace, doc); expect(result.title).toBe('Current synthetic'); expect(result.passages.map(p => p.locator)).toEqual(['paragraph 1', 'paragraph 2']); await expect(repository.read('00000000-0000-4000-8000-000000009999', doc)).rejects.toThrow('unavailable'); });
    it('hides unavailable current documents immediately', async () => { query(`update research_documents set status='unavailable' where id='${doc}'`); expect(await repository.search(workspace, {})).toEqual([]); await expect(repository.read(workspace, doc)).rejects.toThrow('unavailable'); query(`update research_documents set status='available' where id='${doc}'`); });
});
