import {pgTable,uuid,text,timestamp,boolean,index,unique,check} from 'drizzle-orm/pg-core';
import {sql} from 'drizzle-orm';
import {QCS_WORKSPACE_ID} from '../research/contracts';
import {researchIdentifiers,researchDocuments,researchVersions,researchPassages} from './research-schema';
export const researchIdentifierEvidence=pgTable('research_identifier_evidence',{
 id:uuid('id').primaryKey().defaultRandom(),workspaceId:uuid('workspace_id').notNull().default(QCS_WORKSPACE_ID),
 identifierId:uuid('identifier_id').notNull().references(()=>researchIdentifiers.id,{onDelete:'cascade'}),documentId:uuid('document_id').notNull().references(()=>researchDocuments.id),versionId:uuid('version_id').notNull().references(()=>researchVersions.id),passageId:uuid('passage_id').notNull().references(()=>researchPassages.id),reviewedBy:text('reviewed_by').notNull(),reason:text('reason').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),
},table=>[index('research_identifier_evidence_version').on(table.versionId),unique('research_identifier_evidence_identifier_id_version_id_passage_id_key').on(table.identifierId,table.versionId,table.passageId)]);
export const researchCaseTreatments=pgTable('research_case_treatments',{
 id:uuid('id').primaryKey().defaultRandom(),workspaceId:uuid('workspace_id').notNull().default(QCS_WORKSPACE_ID),fromDocumentId:uuid('from_document_id').notNull().references(()=>researchDocuments.id),toDocumentId:uuid('to_document_id').notNull().references(()=>researchDocuments.id),fromVersionId:uuid('from_version_id').notNull().references(()=>researchVersions.id),toVersionId:uuid('to_version_id').notNull().references(()=>researchVersions.id),passageId:uuid('passage_id').notNull().references(()=>researchPassages.id),kind:text('kind').notNull(),reviewedBy:text('reviewed_by'),reason:text('reason').notNull(),available:boolean('available').notNull().default(true),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),
},table=>[index('research_case_treatment_versions').on(table.fromVersionId,table.toVersionId),unique('research_case_treatments_from_version_id_to_version_id_passage_id_kind_key').on(table.fromVersionId,table.toVersionId,table.passageId,table.kind),check('research_case_treatments_kind_check',sql`${table.kind} in ('cites','applies','distinguishes','overrules','appeal')`),check('research_case_treatments_check',sql`${table.fromDocumentId}<>${table.toDocumentId}`)]);
