import type { DraftFinding } from './report-schema';
import type { CoverageEntry,EvidencePassage } from './workflow-types';
import { csvCell,escapeHtml,safeLink } from './exports';
export type ResearchReport={id:string;investigationId:string;runId:string;audience:'internal'|'external';status:'draft'|'reviewed'|'stale';findings:DraftFinding[];coverage:CoverageEntry[];methodology:string;createdAt:string};
export function renderResearchReport(report:ResearchReport,evidence:EvidencePassage[],format:'markdown'|'csv'|'html'):string{
 if(report.status==='stale')throw new Error('Report requires regeneration after a source change');
 const byId=new Map(evidence.map(e=>[e.passageId,e]));
 for(const finding of report.findings)for(const ref of finding.evidence){const p=byId.get(ref.passageId);if(!p||p.versionId!==ref.versionId||p.documentId!==ref.documentId)throw new Error('Report evidence is unavailable');}
 if(format==='csv')return [['Finding','Kind','Review status','Source','URL','Locator','Version','Retrieved','Coverage'],...report.findings.flatMap(f=>f.evidence.length?f.evidence.map(ref=>{const p=byId.get(ref.passageId)!;return [f.text,f.kind,report.status,p.title,p.url,JSON.stringify(p.locator),p.versionId,p.retrievedAt,report.coverage.map(c=>c.state+': '+c.note).join('; ')];}):[[f.text,f.kind,report.status,'','','','','',report.coverage.map(c=>c.state+': '+c.note).join('; ')]])].map(row=>row.map(csvCell).join(',')).join('\r\n');
 const sections=report.findings.map(f=>f.text+' ['+f.kind+']\n'+f.evidence.map(ref=>{const p=byId.get(ref.passageId)!;return p.title+' | '+p.url+' | '+JSON.stringify(p.locator)+' | version '+p.versionId+' | retrieved '+p.retrievedAt+' | '+p.attribution;}).join('\n'));
 if(format==='markdown')return '# QCS research report\n\n'+report.status+' | '+report.audience+'\n\n'+report.methodology+'\n\n'+sections.join('\n\n')+'\n\n## Coverage\n\n'+report.coverage.map(c=>c.state+': '+c.note).join('\n');
 return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><title>QCS research report</title><style>body{font:16px/1.6 Georgia,serif;max-width:900px;margin:40px auto;padding:24px;color:#18382e}h1{font-size:32px}article{break-inside:avoid;border-bottom:1px solid #ccc;padding:20px 0}small{display:block;overflow-wrap:anywhere}@media print{body{margin:0;padding:12mm}}</style><h1>QCS research report</h1><p>'+escapeHtml(report.status+' | '+report.audience)+'</p><p>'+escapeHtml(report.methodology)+'</p>'+report.findings.map(f=>'<article><p>'+escapeHtml(f.text)+'</p><small>'+escapeHtml(f.kind)+'</small>'+f.evidence.map(ref=>{const p=byId.get(ref.passageId)!;return '<small><a href="'+escapeHtml(safeLink(p.url))+'">'+escapeHtml(p.title)+'</a> | '+escapeHtml(JSON.stringify(p.locator)+' | version '+p.versionId+' | retrieved '+p.retrievedAt+' | '+p.attribution)+'</small>';}).join('')+'</article>').join('')+'<h2>Coverage</h2>'+report.coverage.map(c=>'<p>'+escapeHtml(c.state+': '+c.note)+'</p>').join('')+'</html>';
}
