'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import type {ReviewedEntity} from '@/lib/db/research-entities';
import {ActionForm,DataTable,Panel,api,value,type Field,type Row} from './ResearchControls';
type ReviewEvidence={documentId:string;versionId:string;passageId:string;title:string;text:string;locator?:unknown};
type CaseOption={documentId:string;title:string;identifiers:{type:string;value:string}[]};
const base='/api/portal/research';
const input=(name:string,label:string,type:Field['type']='text',initial?:string):Field=>({name,label,type,required:true,value:initial});
/** Directors select actual source passages; internal evidence IDs are never typed into forms. */
export function EntitiesReview({evidence=[],documentId,onReviewed}:{evidence?:ReviewEvidence[];documentId?:string;onReviewed?:()=>void|Promise<void>}){
 const [entities,setEntities]=useState<ReviewedEntity[]>([]),[targets,setTargets]=useState<CaseOption[]>([]),[treatments,setTreatments]=useState<Row[]>([]),[error,setError]=useState('');
 const load=useCallback(async()=>{setEntities(await api<ReviewedEntity[]>(base+'/entities/search'));if(documentId)setTreatments(await api<Row[]>(base+'/case-law/treatment?documentId='+encodeURIComponent(documentId)));},[documentId]);
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Reviews could not be loaded'));},[load]);
 const completed=async()=>{await load();await onReviewed?.();};
 const selectEvidence:Field={name:'passage',label:'Supporting source passage',type:'select',required:true,options:evidence.map(p=>({value:p.passageId,label:p.title+' · '+p.text.slice(0,140)}))};
 const selected=(id:string)=>{const p=evidence.find(item=>item.passageId===id);if(!p)throw new Error('Select available source evidence');return {documentId:p.documentId,versionId:p.versionId,passageId:p.passageId};};
 const fromOptions=[...new Map(evidence.map(p=>[p.documentId,{value:p.documentId,label:p.title}])).values()];
 return <section className="space-y-5" aria-label="Identity and authority review">
  {error&&<p role="alert">{error}</p>}
  <ActionForm title="Find an identity" fields={[{name:'query',label:'Name',type:'text',required:false},{name:'number',label:'Companies House number (optional)',type:'text',required:false}]} button="Search identities" submit={async form=>{const params=new URLSearchParams({query:value(form,'query')});if(value(form,'number')){params.set('scheme','uk-company-number');params.set('value',value(form,'number'));}setEntities(await api<ReviewedEntity[]>(base+'/entities/search?'+params));}}/>
  <DataTable rows={entities as unknown as Row[]} columns={[{key:'displayName',title:'Identity'},{key:'kind',title:'Type'},{key:'confirmed',title:'Review',render:row=>row.confirmed?'Confirmed':'Unconfirmed'},{key:'identifiers',title:'Source-backed identifiers',render:row=>(row.identifiers as ReviewedEntity['identifiers']).map(i=>i.scheme+': '+i.value).join('; ')||'No current identifier evidence'}]}/>
  <ActionForm title="Add an identity for review" fields={[input('displayName','Name'),{name:'kind',label:'Type',type:'select',required:true,options:['company','group','person','project','contract','case','adviser'].map(kind=>({value:kind,label:kind}))},input('jurisdiction','Jurisdiction','text','GB')]} button="Add unconfirmed identity" submit={async form=>{await api(base+'/entities',{displayName:value(form,'displayName'),kind:value(form,'kind'),jurisdiction:value(form,'jurisdiction')});await completed();}}/>
  {!evidence.length?<Panel title="Source evidence required"><p>Retrieve source records in an investigation before confirming an identifier or reviewing legal treatment.</p></Panel>:<>
   <ActionForm title="Confirm an identifier from source evidence" button="Confirm identifier and identity" fields={[{name:'entityId',label:'Identity',type:'select',required:true,options:entities.map(e=>({value:e.id,label:e.displayName+' ('+e.jurisdiction+')'}))},{name:'scheme',label:'Identifier scheme',type:'select',required:true,options:[{value:'uk-company-number',label:'Companies House number'},{value:'lei',label:'Legal Entity Identifier'},{value:'ocid',label:'Procurement OCID'}]},input('value','Exact identifier'),selectEvidence,input('reason','Review rationale','textarea')]} submit={async form=>{await api(base+'/entities/'+value(form,'entityId')+'/identifiers',{scheme:value(form,'scheme'),value:value(form,'value'),evidence:selected(value(form,'passage')),reason:value(form,'reason')});await completed();}}/>
   <Panel title="Selected source material"><div className="space-y-3 max-h-72 overflow-auto">{evidence.map(p=><details key={p.passageId}><summary>{p.title} · {p.text.slice(0,90)}</summary><p className="whitespace-pre-wrap p-3">{p.text}</p></details>)}</div></Panel>
   <ActionForm title="Find an authority being considered" fields={[input('query','Authority name, citation or legal issue')]} button="Find authorities" submit={async form=>setTargets(await api<CaseOption[]>(base+'/case-law?query='+encodeURIComponent(value(form,'query'))))}/>
   <ActionForm title="Review express legal treatment" button="Record reviewed treatment" fields={[{name:'fromDocumentId',label:'Judgment providing the treatment',type:'select',required:true,options:fromOptions},{name:'toDocumentId',label:'Authority being considered',type:'select',required:true,options:targets.map(t=>({value:t.documentId,label:t.title}))},{name:'kind',label:'Express treatment',type:'select',required:true,options:['cites','applies','distinguishes','overrules','appeal'].map(kind=>({value:kind,label:kind}))},selectEvidence,input('targetReference','Exact citation or title as quoted'),input('quotation','Exact supporting quotation','textarea'),input('reason','Review rationale','textarea')]} submit={async form=>{await api(base+'/case-law/treatment',{fromDocumentId:value(form,'fromDocumentId'),toDocumentId:value(form,'toDocumentId'),kind:value(form,'kind'),evidence:selected(value(form,'passage')),targetReference:value(form,'targetReference'),quotation:value(form,'quotation'),reason:value(form,'reason')});await completed();}}/>
   <p className="text-[15px] text-muted">A citation alone records “cites”. Appeal or negative treatment requires express passage evidence and review.</p>
  </>}
  {!!documentId&&<DataTable rows={treatments} columns={[{key:'sourceTitle',title:'Source authority',render:row=><Link href={'/portal/research/case-law/'+row.fromDocumentId} className="underline">{String(row.sourceTitle??'Authority')}</Link>},{key:'kind',title:'Reviewed treatment'},{key:'targetTitle',title:'Authority considered',render:row=><Link href={'/portal/research/case-law/'+row.toDocumentId} className="underline">{String(row.targetTitle??'Authority')}</Link>},{key:'reason',title:'Review rationale'}]}/>}
 </section>;
}
