'use client';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { EvidencePassage } from '@/lib/research/workflow-types';
import { ActionForm, DataTable, Panel, api, date, nullable, value, values, type Row } from './ResearchControls';

export function ResearchIntelligence({ mode }: { mode: 'digests' | 'indexes' }) {
  const [rows, setRows] = useState<Row[]>([]);
  const [investigations, setInvestigations] = useState<Row[]>([]);
  const [investigationId, setInvestigationId] = useState('');
  const [evidence, setEvidence] = useState<EvidencePassage[]>([]);
  const [error, setError] = useState('');
  const selectionSequence = useRef(0);
  const reload = useCallback(async () => {
    try { setRows(await api<Row[]>(`/api/portal/research/${mode}`)); setError(''); }
    catch (e) { setError(e instanceof Error ? e.message : 'Research unavailable'); }
  }, [mode]);
  useEffect(() => { void reload(); if (mode === 'indexes') void api<Row[]>('/api/portal/research/investigations').then(setInvestigations).catch(e => setError(String(e))); }, [mode, reload]);
  async function selectInvestigation(id: string) {
    const sequence = ++selectionSequence.current;
    setInvestigationId(id); setEvidence([]);
    if (!id) return;
    try { const result = await api<{ evidence: EvidencePassage[] }>(`/api/portal/research/investigations/${id}`); if (sequence === selectionSequence.current) setEvidence(result.evidence); }
    catch (e) { if (sequence === selectionSequence.current) setError(e instanceof Error ? e.message : 'Evidence unavailable'); }
  }
  return <div className="mx-auto max-w-6xl space-y-8">
    <Link href="/portal/research" className="text-[15px] underline">Research</Link>
    <h1 className="font-sans text-4xl">{mode === 'digests' ? 'Weekly internal research digests' : 'Evidence and methodology indexes'}</h1>
    {error && <p role="alert">{error}</p>}
    {mode === 'digests' && <><p className="text-muted">The research scheduler records one internal selection each week. Source availability and suppressions are checked again when you open it.</p>{!rows.length && <p>No weekly digest has been generated by the scheduler yet.</p>}{rows.map(d => <Panel key={String(d.id)} title={'Week commencing ' + date(d.week_start)}>
      <p className="text-[15px]">{String(d.methodology)}</p>
      <p className="text-[15px]">{String(d.unavailableSignals)} original entries are now unavailable or suppressed.</p>
      <DataTable rows={d.signals as Row[]} columns={[{ key: 'organisation', title: 'Identity' }, { key: 'event_type', title: 'Event' }, { key: 'status', title: 'Review state' }, { key: 'investigation_id', title: 'Evidence', render: s => <Link className="underline" href={'/portal/research/investigations/' + s.investigation_id}>Open investigation</Link> }]} />
      <h3 className="font-sans text-xl">Calendar reminders</h3><DataTable rows={d.calendar as Row[]} columns={[{ key: 'kind', title: 'Event' }, { key: 'proposed_date', title: 'Proposed date', render: c => date(c.proposed_date) }, { key: 'state', title: 'Review state' }]} />
      <details><summary className="cursor-pointer">Source coverage when generated</summary><DataTable rows={d.source_coverage as Row[]} columns={[{ key: 'sourceId', title: 'Source ID' }, { key: 'status', title: 'Acquisition state' }, { key: 'lastSuccessAt', title: 'Latest successful retrieval', render: c => date(c.lastSuccessAt) }]} /></details>
    </Panel>)}</>}
    {mode === 'indexes' && <>
      <p className="text-muted">Record the population, comparable cohort, source selection and missing material before publishing a count. A rate requires an evidenced denominator.</p>
      <label className="block">Investigation<select className="mt-2 block w-full rounded border border-text/25 p-2" value={investigationId} onChange={e => void selectInvestigation(e.target.value)}><option value="">Choose</option>{investigations.map(i => <option key={String(i.id)} value={String(i.id)}>{String(i.question)}</option>)}</select></label>
      {investigationId && <ActionForm key={investigationId} title="Create an evidence index" button="Save index" fields={[
        { name: 'kind', label: 'Index subject', type: 'select', required: true, options: [{ value: 'adjudication', label: 'Published adjudication decisions' }, { value: 'gateway', label: 'Gateway application cohort' }] },
        { name: 'population', label: 'Population actually covered', type: 'textarea', required: true },
        { name: 'cohort', label: 'Comparable cohort', required: true },
        { name: 'from', label: 'Period starts', type: 'date', required: true },
        { name: 'to', label: 'Period ends', type: 'date', required: true },
        { name: 'inclusionRules', label: 'Inclusion and exclusion rules', type: 'textarea', required: true },
        { name: 'missingSources', label: 'Missing sources and population', type: 'textarea', required: true },
        { name: 'denominator', label: 'Evidenced population denominator (optional)', type: 'number', min: 1 },
        { name: 'denominatorEvidence', label: 'Passages establishing the denominator', type: 'checks', options: evidence.map(e => ({ value: e.passageId, label: e.title + ' · ' + e.text.slice(0,80) })) },
        { name: 'observations', label: 'Included source records', type: 'checks', options: evidence.map(e => ({ value: e.passageId, label: e.title + ' · ' + (e.eventAt ?? e.publishedAt ?? 'Date not published') })) },
      ]} submit={async v => {
        const selected = evidence.filter(e => values(v, 'observations').includes(e.passageId));
        const refs = (e: EvidencePassage) => ({ documentId: e.documentId, versionId: e.versionId, passageId: e.passageId });
        if (selected.some(e => !e.eventAt && !e.publishedAt)) throw new Error('Each selected record needs an evidenced event or publication date. Resolve undated records before indexing.');
        await api('/api/portal/research/indexes', { investigationId, kind: value(v, 'kind'), population: value(v, 'population'), cohort: value(v, 'cohort'), from: value(v, 'from'), to: value(v, 'to'), inclusionRules: value(v, 'inclusionRules'), missingSources: value(v, 'missingSources'), denominator: nullable(v, 'denominator') ? Number(value(v, 'denominator')) : null, denominatorEvidence: evidence.filter(e => values(v, 'denominatorEvidence').includes(e.passageId)).map(refs), observations: selected.map(e => ({ eventKey: e.documentId, date: (e.eventAt ?? e.publishedAt)!.slice(0,10), included: true, evidence: [refs(e)] })) });
        await reload();
      }} />}
      {rows.map(row => { const s = row.specification as Row, summary = row.summary as Row; return <Panel key={String(row.id)} title={String(s.kind) + ' · ' + String(s.cohort)}>
        <p>{String(s.population)} · {date(s.from)} to {date(s.to)}</p><p>{String(s.inclusionRules)}</p><p>Missing: {String(s.missingSources)}</p>
        <p className="font-sans text-2xl">{String(summary.numerator)} included events{summary.denominator !== null ? ' / ' + summary.denominator + ' (' + Math.round(Number(summary.rate) * 100) + '%)' : '. Population denominator not established.'}</p>
        <p>{String(summary.duplicatesRemoved)} duplicates removed; {String(summary.outsidePeriod)} outside period; {String(summary.excluded)} excluded.</p><p className="text-[15px]">{String(summary.warning)}</p>
        <div className="flex flex-wrap gap-4">{(row.evidence as { passageId: string }[]).map(e => <Link key={e.passageId} href={'/portal/research/evidence/' + e.passageId} className="text-[15px] underline">Source passage {e.passageId.slice(0,8)}</Link>)}</div>
      </Panel>; })}
    </>}
  </div>;
}
