import { useApi } from '../hooks/useApi'
import { usePageTitle } from '../hooks/usePageTitle'
import { Page, StatePanel, TableFrame } from '../components/Ui'
import { IndexPlot } from '../components/IndexPlot'
import { formatDate, formatDateTime, formatIndexLabel, formatNumber, formatReportingWindow, sentence } from '../format'
import type { IndicesResponse } from '../types'

export default function Indices() {
  usePageTitle('Indices')
  const { data, loading, error, reload } = useApi<IndicesResponse>('/api/indices')
  return <Page title="Indices" eyebrow="Published market measures">{loading && !data ? <StatePanel state="loading" /> : error ? <StatePanel state="error" message={error} onRetry={reload} /> : data && <>
    <section className="coverage"><h2>Methodology</h2><p>{data.methodology ?? 'Methodology has not been supplied.'}</p></section>
    {!data.series.length ? <StatePanel state="empty" title="No index series available" message="Meritus has not received enough categorised source data to publish a series. Empty data is not a zero index." /> : data.series.map((series, index) => <section className="list-panel" key={`${series.source_id}-${series.kind}-${series.category}-${index}`}><h2>{formatIndexLabel(series.category)}</h2><p>{formatIndexLabel(series.source_id)} · {formatIndexLabel(series.kind)} · {series.unit ?? 'Unit not recorded'} · {sentence(series.scope)}</p><IndexPlot series={series} /><TableFrame label={`${formatIndexLabel(series.category)} published points`}><table><thead><tr><th scope="col">Window</th><th scope="col">Period</th><th scope="col">Value</th><th scope="col">Published and observed</th><th scope="col">Source</th></tr></thead><tbody>{series.points.map((point, pointIndex) => <tr key={`${point.observation_id}-${pointIndex}`}><td title={point.window}>{formatReportingWindow(point.window)}</td><td>{formatReportingWindow(point.period_start)} to {formatReportingWindow(point.period_end)}</td><td className="large-data">{formatNumber(point.value)}{point.value != null && ` ${series.unit ?? ''}`}</td><td>{formatDate(point.published_at)}<span className="cell-meta">Observed {formatDateTime(point.observed_at)}</span></td><td>{point.source_url ? <a href={point.source_url} target="_blank" rel="noreferrer">Open published source</a> : 'No source link supplied'}<span className="cell-meta">Revision {point.revision ?? 'not recorded'}</span><code>{point.record_id}</code></td></tr>)}</tbody></table></TableFrame></section>)}
    <section className="coverage index-coverage"><h2>Coverage</h2>{data.coverage.length ? <ul>{data.coverage.map((item, index) => <li key={`${item.source_id}-${item.category}-${index}`}><strong>{formatIndexLabel(item.source_id)} · {formatIndexLabel(item.category)} · {item.unit ?? 'Unit not recorded'}</strong><span>{item.point_count} published {item.point_count === 1 ? 'point' : 'points'} · {formatReportingWindow(item.first_window)} to {formatReportingWindow(item.last_window)}</span><span>Windows: {item.windows.map(formatReportingWindow).join(', ')}</span></li>)}</ul> : <p>No coverage metadata was supplied by the API.</p>}</section>
    <section className="coverage"><h2>Suppression</h2><p>{data.suppressed_points ?? data.suppressed?.length ?? 0} suppressed {(data.suppressed_points ?? data.suppressed?.length) === 1 ? 'point' : 'points'}</p>{Boolean(data.suppressed?.length) && <TableFrame label="Suppressed index points"><table><thead><tr><th scope="col">Source and category</th><th scope="col">Window</th><th scope="col">Reason</th></tr></thead><tbody>{data.suppressed.map((point, index) => <tr key={`${point.observation_id}-${index}`}><td>{formatIndexLabel(point.source_id)} · {formatIndexLabel(point.category)}</td><td title={point.window}>{formatReportingWindow(point.window)}</td><td>{sentence(point.reason)}</td></tr>)}</tbody></table></TableFrame>}</section>
  </>}</Page>
}
