import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Entity, EntityBrief, EvidenceLineage, Matter, OpportunitiesResponse } from '../types'
import { useApi } from '../hooks/useApi'
import { DataAuthenticity, Pagination, StatePanel, Status, TableFrame } from './Ui'
import { EntityPicker } from './EntityPicker'
import { formatDateTime, sentence } from '../format'

function EntityLink({ entity }: { entity: EntityBrief }) { return <Link to={`/entities/${encodeURIComponent(entity.id)}`}>{entity.name}</Link> }
function MatterReference({ matter }: { matter: Matter }) { return <>{matter.reference ?? 'No matter reference'}{matter.entity_id && <span className="cell-meta"><Link to={`/entities/${encodeURIComponent(matter.entity_id)}`}>Open matter entity</Link></span>}</> }
function Lineage({ value }: { value: EvidenceLineage }) { return <div>{value.source_url && <a href={value.source_url} target="_blank" rel="noreferrer">Open source evidence</a>}<span className="cell-meta">{sentence(value.source_id)}{value.record_id && <> · record <code>{value.record_id}</code></>}</span>{value.observation_id && <span className="cell-meta">Observation <code>{value.observation_id}</code></span>}{value.relationship_id && <span className="cell-meta">Relationship <code>{value.relationship_id}</code></span>}</div> }
export function OpportunitiesPanel({ entities, disabled, version }: { entities: Entity[]; disabled: boolean; version: number }) {
  const [entityId, setEntityId] = useState(''); const [page, setPage] = useState(1)
  const params = new URLSearchParams({ page: String(page), page_size: '25' }); if (entityId) params.set('entity_id', entityId)
  const { data, loading, error, reload } = useApi<OpportunitiesResponse>(`/api/opportunities?${params}`)
  useEffect(() => { if (version) reload() }, [version, reload])
  const total = data ? Math.max(...Object.values(data.totals)) : 0
  return <section className="list-panel"><h2>Exposure and relationship review</h2><EntityPicker id="opportunity_entity" label="Opportunity entity" value={entityId} onChange={value => { setEntityId(value); setPage(1) }} entities={entities} disabled={disabled} optional />{loading && !data ? <StatePanel state="loading" /> : error ? <StatePanel state="error" message={error} onRetry={reload} /> : data && <>
    <p>{data.coverage}</p><p>As of {formatDateTime(data.as_of)}</p><DataAuthenticity truncated={data.truncated} />
    <h3>Possible project exposure</h3>{!data.project_exposures.length ? <p>No documented project exposures on this page.</p> : <TableFrame label="Possible project exposures"><table><thead><tr><th>Supplier and project</th><th>Review prompt</th><th>Evidence lineage</th></tr></thead><tbody>{data.project_exposures.map((item, index) => <tr key={`${item.relationship_id}-${index}`}><td><EntityLink entity={item.supplier} /><span className="cell-meta">Supplier on <EntityLink entity={item.project} /></span>{item.contract_id && <span className="cell-meta">Contract {item.contract_id}</span>}</td><td><Status value={item.status} /><p>{item.commercial_relevance}</p><p>Supplier evidence is not a finding about the main contractor.</p></td><td><Lineage value={item.lineage.insolvency} /><Lineage value={item.lineage.project_role} /></td></tr>)}</tbody></table></TableFrame>}
    <h3>Possible introduction routes</h3>{!data.introduction_routes.length ? <p>No documented introduction routes on this page.</p> : <TableFrame label="Possible introduction routes"><table><thead><tr><th>Professional and party</th><th>Matter</th><th>Review prompt</th><th>Evidence lineage</th></tr></thead><tbody>{data.introduction_routes.map(item => <tr key={item.relationship_id}><td><EntityLink entity={item.professional} /><span className="cell-meta">{sentence(item.professional_role)} for <EntityLink entity={item.party} /></span></td><td><MatterReference matter={item.matter} /></td><td><Status value={item.status} /><p>{item.reason}</p></td><td><Lineage value={item.lineage} /></td></tr>)}</tbody></table></TableFrame>}
    <h3>Conflict clearance prompts</h3>{!data.conflict_review_prompts.length ? <p>No overlapping professional roles on this page.</p> : <TableFrame label="Conflict clearance prompts"><table><thead><tr><th>Professional and parties</th><th>Matters</th><th>Human clearance</th><th>Evidence lineage</th></tr></thead><tbody>{data.conflict_review_prompts.map((item, index) => <tr key={`${item.relationship_ids.join('-')}-${index}`}><td><EntityLink entity={item.professional} />{item.parties.map(party => <span key={party.id} className="cell-meta"><EntityLink entity={party} /></span>)}</td><td>{item.matters.map((matter, index) => <p key={index}><MatterReference matter={matter} /></p>)}</td><td><Status value={item.status} /><p>{sentence(item.overlap)}. {item.prompt}</p></td><td>{item.lineages.map((lineage, index) => <Lineage key={index} value={lineage} />)}</td></tr>)}</tbody></table></TableFrame>}
    <p>Totals: {data.totals.project_exposures} project exposures, {data.totals.introduction_routes} introduction routes and {data.totals.conflict_review_prompts} conflict clearance prompts.</p><Pagination page={data.page} pageSize={data.page_size} total={total} onPage={setPage} />
  </>}</section>
}
